name: Run Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: uv sync --group dev

    - name: Run tests
      run: uv run pytest

    - name: Run linting
      run: uv run ruff check

    - name: Run type checking
      run: uv run pyright
